version: '3'
services:
  wishlist:
    build:
      context: https://github.com/Jannik6/simple-wishlist.git
      pull: true
    container_name: wishlist_jannik
    hostname: wishlist_jannik
    ports:
      - 9900:8092
    environment:
      - DBHOST=mongodb:27017
      - CURRENCY=EUR
      - LIST_NAME=Wunschliste Jannik
      - LIST_TYPE=bday
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: wishlist-db_jannik
    hostname: mongodb_jannik
    volumes:
      - /mnt/user/appdata/wishlist/mongodb_jannik:/data/db